config/routes.rb
Animator::Application.routes.draw do
  resources :companies

  resources :animations

  get "home/index"
root :to => "home#index"

end

app/models/animation.rb
class Animation < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/animations_controller.rb
class AnimationsController < ApplicationController
  # GET /animations
  # GET /animations.xml
  def index
    @animations = Animation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @animations }
    end
  end

  # GET /animations/1
  # GET /animations/1.xml
  def show
    @animation = Animation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @animation }
    end
  end

  # GET /animations/new
  # GET /animations/new.xml
  def new
    @animation = Animation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @animation }
    end
  end

  # GET /animations/1/edit
  def edit
    @animation = Animation.find(params[:id])
  end

  # POST /animations
  # POST /animations.xml
  def create
    @animation = Animation.new(params[:animation])

    respond_to do |format|
      if @animation.save
        format.html { redirect_to(@animation, :notice => 'Animation was successfully created.') }
        format.xml  { render :xml => @animation, :status => :created, :location => @animation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @animation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /animations/1
  # PUT /animations/1.xml
  def update
    @animation = Animation.find(params[:id])

    respond_to do |format|
      if @animation.update_attributes(params[:animation])
        format.html { redirect_to(@animation, :notice => 'Animation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @animation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /animations/1
  # DELETE /animations/1.xml
  def destroy
    @animation = Animation.find(params[:id])
    @animation.destroy

    respond_to do |format|
      format.html { redirect_to(animations_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.xml
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.xml
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.xml
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.xml
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to(@company, :notice => 'Company was successfully created.') }
        format.xml  { render :xml => @company, :status => :created, :location => @company }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.xml
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to(@company, :notice => 'Company was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.xml
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to(companies_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/animations_helper.rb
module AnimationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/animations/_form.html.erb
<%= form_for(@animation) do |f| %>
  <% if @animation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animation.errors.count, "error") %> prohibited this animation from being saved:</h2>

      <ul>
      <% @animation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :salary %><br />
    <%= f.text_field :salary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/animations/edit.html.erb
<h1>Editing animation</h1>

<%= render 'form' %>

<%= link_to 'Show', @animation %> |
<%= link_to 'Back', animations_path %>

app/views/animations/index.html.erb
<h1>Listing animations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Salary</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @animations.each do |animation| %>
  <tr>
    <td><%= animation.name %></td>
    <td><%= animation.age %></td>
    <td><%= animation.salary %></td>
    <td><%= link_to 'Show', animation %></td>
    <td><%= link_to 'Edit', edit_animation_path(animation) %></td>
    <td><%= link_to 'Destroy', animation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Animation', new_animation_path %>

app/views/animations/new.html.erb
<h1>New animation</h1>

<%= render 'form' %>

<%= link_to 'Back', animations_path %>

app/views/animations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @animation.name %>
</p>

<p>
  <b>Age:</b>
  <%= @animation.age %>
</p>

<p>
  <b>Salary:</b>
  <%= @animation.salary %>
</p>


<%= link_to 'Edit', edit_animation_path(@animation) %> |
<%= link_to 'Back', animations_path %>

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :AnimatorName %><br />
    <%= f.text_field :AnimatorName %>
  </div>
  <div class="field">
    <%= f.label :Age %><br />
    <%= f.text_field :Age %>
  </div>
  <div class="field">
    <%= f.label :salary %><br />
    <%= f.text_field :salary %>
  </div>
  <div class="field">
    <%= f.label :DOB %><br />
    <%= f.date_select :DOB %>
  </div>
  <div class="field">
    <%= f.label :animation %><br />
    <%= f.text_area :animation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <tr>
    <th>Animatorname</th>
    <th>Age</th>
    <th>Salary</th>
    <th>Dob</th>
    <th>Animation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= company.AnimatorName %></td>
    <td><%= company.Age %></td>
    <td><%= company.salary %></td>
    <td><%= company.DOB %></td>
    <td><%= company.animation %></td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Animatorname:</b>
  <%= @company.AnimatorName %>
</p>

<p>
  <b>Age:</b>
  <%= @company.Age %>
</p>

<p>
  <b>Salary:</b>
  <%= @company.salary %>
</p>

<p>
  <b>Dob:</b>
  <%= @company.DOB %>
</p>

<p>
  <b>Animation:</b>
  <%= @company.animation %>
</p>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/home/index.html.erb
<h1>Animation creation</h1> <%= link_to "Company", companies_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Animator</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>